# =============================================================================
# Google Cloud Run Service Configuration for Chantilly Agent
# =============================================================================
#
# Security Features:
# - Service account with minimal permissions
# - VPC connector for Firestore private access
# - Environment variables from Secret Manager
# - Resource limits and autoscaling
# - Health checks and readiness probes
#
# DEPLOYMENT:
# gcloud run services replace cloudrun.yaml --region=us-central1
#
# PREREQUISITES:
# 1. Create secrets in Secret Manager:
#    - chantilly-gemini-api-key
#    - chantilly-bitrix24-webhook
#    - chantilly-bitrix24-secret
# 2. Create VPC connector (optional for Firestore private access):
#    gcloud compute networks vpc-access connectors create chantilly-connector \
#      --network=default --region=us-central1 --range=10.8.0.0/28
# 3. Create service account:
#    gcloud iam service-accounts create chantilly-agent-sa \
#      --display-name="Chantilly Agent Service Account"
# 4. Grant necessary permissions (see below)
#
# =============================================================================

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chantilly-agent
  labels:
    app: chantilly-agent
    environment: production
    version: "1.0.0"
  annotations:
    # Allow unauthenticated access (webhook endpoint is public)
    # Individual routes can require authentication via middleware
    run.googleapis.com/ingress: all
    run.googleapis.com/description: "Morgan AI Agent - Multi-platform AI assistant"

spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: "1"  # Keep 1 instance warm
        autoscaling.knative.dev/maxScale: "10"  # Max 10 instances
        autoscaling.knative.dev/target: "80"  # Target 80 concurrent requests per instance

        # Resource limits
        run.googleapis.com/cpu-throttling: "false"  # Always allocate CPU

        # VPC configuration (OPTIONAL - uncomment if using VPC connector)
        # run.googleapis.com/vpc-access-connector: chantilly-connector
        # run.googleapis.com/vpc-access-egress: private-ranges-only

        # Execution environment
        run.googleapis.com/execution-environment: gen2

    spec:
      # Service account - using default Compute Engine service account
      # Format: PROJECT_NUMBER-compute@developer.gserviceaccount.com
      # Cloud Run uses this automatically if serviceAccountName is not specified
      # Grant required roles to this SA via IAM (see permissions section below)

      # Container timeout (15 minutes max for complex tasks)
      timeoutSeconds: 900

      containers:
      - name: chantilly-agent
        # Image from Google Container Registry or Artifact Registry
        image: gcr.io/chantilly-agent-morgan/chantilly-agent:latest

        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP

        # Resource limits
        resources:
          limits:
            cpu: "2"        # 2 vCPU
            memory: "2Gi"   # 2GB RAM
          requests:
            cpu: "1"        # Minimum 1 vCPU
            memory: "1Gi"   # Minimum 1GB RAM

        # Environment variables
        env:
        # Basic configuration
        - name: NODE_ENV
          value: "production"

        - name: PORT
          value: "8080"

        - name: LOG_LEVEL
          value: "info"

        - name: GOOGLE_CLOUD_PROJECT
          value: "chantilly-agent-morgan"

        - name: FIRESTORE_DATABASE_ID
          value: "(default)"

        # Platform Integration Flags
        - name: ENABLE_BITRIX24_INTEGRATION
          value: "false"

        - name: ENABLE_GOOGLE_CHAT_INTEGRATION
          value: "true"

        - name: ENABLE_ASANA_INTEGRATION
          value: "true"

        # Agent Identity
        - name: AGENT_NAME
          value: "morgan"

        # Feature flags
        - name: USE_DB_PROMPTS
          value: "false"

        - name: REASONING_MEMORY_ENABLED
          value: "true"

        - name: ENABLE_VECTOR_SEARCH
          value: "true"

        - name: ENABLE_SEMANTIC_TEMPLATES
          value: "true"

        - name: ENABLE_SEMANTIC_TOOLS
          value: "true"

        # Rate limits
        - name: RATE_LIMIT_PER_SECOND
          value: "2"

        - name: RATE_LIMIT_PER_10MIN
          value: "10000"

        - name: QUEUE_MAX_RETRIES
          value: "3"

        # API Keys and Secrets (set via Cloud Run Console)
        # Set these in: Cloud Run Console > Edit & Deploy > Variables & Secrets
        - name: GEMINI_API_KEY
          value: "YOUR_GEMINI_API_KEY"  # Replace via console

        # Google Workspace Chat Configuration
        - name: GOOGLE_CHAT_PROJECT_ID
          value: "chantilly-agent-morgan"

        - name: GOOGLE_CHAT_PROJECT_NUMBER
          value: "YOUR_PROJECT_NUMBER"  # Replace via console

        # NOTE: GOOGLE_APPLICATION_CREDENTIALS not needed in Cloud Run
        # Application Default Credentials (ADC) automatically uses the service account

        # Asana Configuration
        - name: ASANA_ACCESS_TOKEN
          value: "YOUR_ASANA_PAT_TOKEN"  # Replace via console

        - name: ASANA_WORKSPACE_GID
          value: "YOUR_WORKSPACE_GID"  # Replace via console

        - name: ASANA_BOT_EMAIL
          value: "morgan-bot@yourdomain.com"  # Replace via console

        - name: ASANA_WEBHOOK_SECRET
          value: "YOUR_WEBHOOK_SECRET"  # Replace via console

        # JWT Authentication
        - name: JWT_SECRET
          value: "YOUR_JWT_SECRET"  # Replace via console (generate a long random string)

        - name: JWT_EXPIRATION
          value: "24h"

        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
            - name: User-Agent
              value: "GoogleCloudRun/HealthCheck"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1

        # Readiness probe
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
            - name: User-Agent
              value: "GoogleCloudRun/ReadinessCheck"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        # Startup probe (for initial container startup)
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12  # 12 * 5s = 60s max startup time
          successThreshold: 1

# =============================================================================
# Service Account Permissions (IAM)
# =============================================================================
#
# Runtime Service Account: Default Compute Engine Service Account
# Format: PROJECT_NUMBER-compute@developer.gserviceaccount.com
# Example: 123456789012-compute@developer.gserviceaccount.com
#
# REQUIRED: Grant these permissions via Cloud Console
#
# Steps:
# 1. Go to Cloud Console > IAM & Admin > IAM
# 2. Find the Compute Engine default service account (ends with -compute@developer.gserviceaccount.com)
# 3. Click the Edit button (pencil icon)
# 4. Add the following roles:
#
#    ✅ Cloud Datastore User
#       Why: Read/write access to Firestore database
#
#    ✅ Vertex AI User
#       Why: Access Gemini API and embeddings service
#
#    ✅ Logs Writer
#       Why: Write application logs to Cloud Logging
#
#    ✅ Cloud Tasks Enqueuer
#       Why: Create background tasks for async processing
#
# 5. Click Save
#
# Note: The default compute service account may already have some of these roles.
# The application uses Application Default Credentials (ADC) which automatically
# inherits permissions from this service account when running on Cloud Run.
#
# =============================================================================
# Environment Variables Setup
# =============================================================================
#
# Set these variables via Cloud Run Console after deployment:
#
# 1. Go to Cloud Run > chantilly-agent-morgan > Edit & Deploy
# 2. Go to Variables & Secrets tab
# 3. Set the following environment variables:
#
#    Required:
#    - GEMINI_API_KEY: Your Gemini API key from Google AI Studio
#    - GOOGLE_CHAT_PROJECT_NUMBER: Your GCP project number
#    - ASANA_ACCESS_TOKEN: Asana bot user PAT token
#    - ASANA_WORKSPACE_GID: Your Asana workspace GID
#    - ASANA_BOT_EMAIL: Your Asana bot user email
#    - ASANA_WEBHOOK_SECRET: Random secret for webhook verification
#    - JWT_SECRET: Random 64+ character string for JWT signing
#
# NOTE: GOOGLE_APPLICATION_CREDENTIALS is NOT needed in Cloud Run.
# The application automatically uses Application Default Credentials (ADC)
# which inherits from the default Compute Engine service account.
#
# =============================================================================
